### ISSUE TITLE
Issues on x64 builds

### ISSUE THREAD

**Issue by LuisAntonRebollo** [GarageGames/Torque3D#1144]
### OSX problems
- [x] @jamesu report: https://github.com/GarageGames/Torque3D/commit/4e9034854d057f745f7449502cbad03a3fe8b76e#commitcomment-9516570 See  #1149
- [x] @jamesu report: https://github.com/GarageGames/Torque3D/commit/fcf7bee64af8dd7b07696bd0bcb99db8dc56b451#commitcomment-9516353 See  #1149
### Changes for new types
- [x] Create a new T3D typedef for `uintptr_t` and `intptr_t` See  #1149
- [ ] Rethink T3D using a ptr to store `SimObjectId` https://github.com/GarageGames/Torque3D/commit/4e9034854d057f745f7449502cbad03a3fe8b76e#commitcomment-9517497

**Comment by JeffProgrammer** [comment]
some carbon things might have to be taken out. we should really replace the whole platformMac from being carbon based to cocoa based as that's both i386 and x86_64
