### ISSUE TITLE
Add OpenGL 3.2 renderer

### ISSUE THREAD

**Issue by LuisAntonRebollo** [GarageGames/Torque3D#587]
Based on https://github.com/BeamNG/Torque3D/tree/dev_linux_opengl

For easy testing, check [https://github.com/BeamNG/Torque3D/tree/development_opengl](https://github.com/BeamNG/Torque3D/tree/development_opengl) a branch with T3D development + all OpenGL PRs

It's better review all PRs but not merge. We can add a comment `For merge` or `Aproved` and merge all at same time. We can track here the `Aproved` PRs.

Some code are very old, let me revise all work and add a bit of related information. I can mark as `Final Review` for we can focus our work.

It's desirable we merge as fast we can, for have time to resolve any future issue before Torque3D 3.7 release.

Separate in small PRs:
- [x] Use GFXDevice::setupGenericShaders for support non Fixed Fuction Pipelines. #608 
- [x] Add sampler names to Templates ShaderData declarations necesary for OpenGL. #611
- [x] Use shader data for get sampler register in CloudLayer and BasicClouds. #618 
- [x] Add RenderPassData::mSamplerNames for OpenGL code. Not used on DX9. #620 
- [x] Handle texel-pixel offset with diferents graphics APIs. #622 
- [x] Remove GFXDevice::disableShader. #924 
- [x] Add sampler names to ShaderData. #925 
- [x] Fix PrimBuild with non Fixed Function Pipeline. #926 
- [x] Add GFXDevice::setupGenericShader for fix render on non FFP. #927 
- [x] Change RenderParticleMgr for use sampler names #928 
- [x] Remove unnecesary code for handle OpenGL #929 
- [x] Separate OpenGL code from Linux or Mac. #930 
- [x] Set correct terrain layer texture format. #931 
- [x] Reduce innecesary changes on Render Target textures. #932 
- [x] Changes on ShaderGen for generate GLSL shaders. #933 
- [x] Changes on PostFX for OpenGL. #934 
- [x] Fix imposter capture on OpenGL. #935 
- [x] GLEW library for OpenGL. #936 
- [x] Increase FrameBuffer size for use on OpenGL. #937 
- [x] Remove old/unused OpenGL files. #938 
- [x] Templates changes for OpenGL shaders. #939 
- [x] Add/Activate OpenGL render. #940 
- [x] Merge all OpenGL PRs
