### ISSUE TITLE
Add support for Linux / SteamOS

### ISSUE THREAD

**Issue by LuisAntonRebollo** [GarageGames/Torque3D#588]
Create a clean branch based on https://github.com/BeamNG/Torque3D/tree/dev_linux_opengl

* [x]  Add library SDL2 #1107 
* [x]  Modified files for SDL2. #1108 
* [x]  PlatformSDL #1109 
* [x]  Changes for linux #1110 
* [x]  Linux #1111 
* [x] Update CI server
* [x] ~~Update Qt Project Manager~~
* [x] Write docs on T3D Wiki
